#!/usr/bin/env python3
"""
Compare coefficients for the threshold projection experiment.

This script reads the CSV generated by degree_scaling_thresh_proj.py when
run with the "double points" setting (npts = 2 * degree), and produces a
scatter plot comparing:

  - the polynomial coefficients used for the convex fit ("coef_full")
  - the recovered Chebyshev coefficients of the retracted polynomial
    obtained from the QSP phase angles ("phi_proc")

For a chosen degree (default: the largest degree present in the CSV),
it plots:

  x-axis: coefficient index
  y-axis: coefficient value

Colors:
  - Polynomial coefficients: BLUE ("our favorite shade of blue")
  - Retracted polynomial coefficients: MAIZE ("our favorite shade of maize")
"""

import argparse
import json
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from numpy.polynomial import chebyshev as cheb

from qsppack.utils import get_entry


BLUE = "#0072B2"
MAIZE = "#E69F00"


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Compare polynomial and retracted polynomial coefficients "
            "for the threshold projection experiment."
        )
    )
    parser.add_argument(
        "--csv",
        type=str,
        default=None,
        help=(
            "Path to CSV file produced by degree_scaling_thresh_proj.py with "
            "npts = 2 * degree (default: "
            "explorations/recovery/data/degree_scaling_thresh_proj_2x.csv)."
        ),
    )
    parser.add_argument(
        "--degree",
        type=int,
        default=None,
        help=(
            "Degree to visualize (default: largest degree present in the CSV)."
        ),
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help=(
            "Output figure path "
            "(default: explorations/recovery/figures/compare_coeffs_thresh_proj.pdf)."
        ),
    )
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(script_dir, "data")
    figures_dir = os.path.join(script_dir, "figures")

    # Resolve CSV path (use the 2x CSV by default).
    if args.csv is None:
        csv_path = os.path.join(data_dir, "degree_scaling_thresh_proj_2x.csv")
    else:
        csv_path = args.csv

    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    # Resolve output figure path.
    # We only display the figure interactively to avoid cluttering the figures
    # directory; we do not save to disk by default.

    df = pd.read_csv(csv_path)
    required_cols = {"coef_full", "phi_proc", "degree", "parity"}
    missing = required_cols.difference(df.columns)
    if missing:
        raise ValueError(
            f"CSV must contain columns {sorted(required_cols)}, "
            f"but is missing {sorted(missing)}."
        )

    # Select the desired degree (default: largest).
    if args.degree is None:
        row = df.sort_values("degree").iloc[-1]
    else:
        matches = df[df["degree"] == args.degree]
        if matches.empty:
            raise ValueError(
                f"Requested degree {args.degree} not found in CSV {csv_path}."
            )
        row = matches.iloc[0]

    degree = int(row["degree"])
    parity = int(row["parity"])
    coef_full = np.asarray(json.loads(row["coef_full"]), dtype=float)
    phi_proc = np.asarray(json.loads(row["phi_proc"]), dtype=float)

    # Reconstruct the retracted polynomial from the phase angles by:
    #   1. Evaluating the QSP approximation on a dense grid using get_entry
    #   2. Fitting Chebyshev coefficients to that function (chebfit)
    #
    # We use the same convention as in degree_scaling_thresh_proj.py:
    # targetPre=False (imaginary-part QSP polynomial), typePhi='full'.
    m = 4 * degree + 1
    x_sample = np.linspace(0.0, 1.0, m)
    opts_eval = {
        "method": "NLFT",
        "targetPre": False,
        "parity": parity,
        "typePhi": "full",
    }
    qsp_vals = get_entry(x_sample, phi_proc, opts_eval)

    # Fit Chebyshev coefficients of degree `degree` to the sampled QSP polynomial.
    coef_retracted_full = cheb.chebfit(x_sample, qsp_vals, degree)

    # Only plot even-index Chebyshev coefficients to avoid zeros at odd indices.
    even_idx = np.arange(0, coef_full.size, 2, dtype=int)
    coef_full_even = coef_full[even_idx]
    coef_retracted_even = coef_retracted_full[even_idx]

    plt.rcParams["font.family"] = "serif"
    plt.rcParams["font.size"] = 12

    fig, ax = plt.subplots(figsize=(8, 6))

    # Polynomial coefficients (BLUE)
    ax.scatter(
        even_idx,
        np.abs(coef_full_even),
        color=BLUE,
        s=30,
        marker="o",
        label="Polynomial coefficients",
    )

    # Retracted polynomial coefficients (MAIZE)
    ax.scatter(
        even_idx,
        np.abs(coef_retracted_even),
        color=MAIZE,
        s=30,
        marker="o",
        label="Retracted polynomial coefficients",
    )

    ax.set_xlabel("Index")
    ax.set_ylabel("Value")
    ax.set_title(f"Threshold projection coefficients (degree = {degree})")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")
    ax.set_yscale("log")

    fig.tight_layout()

    # Sanity check: plot in x-space both
    #   - the QSP evaluation qsp_vals, and
    #   - the polynomial defined by the retracted coefficients.
    x_plot = np.linspace(0.0, 1.0, 1000)
    vals_retracted = cheb.chebval(x_plot, coef_retracted_full)

    fig2, ax2 = plt.subplots(figsize=(8, 4))
    # QSP evaluation (direct from phases, on the original sample grid)
    ax2.plot(x_sample, qsp_vals, color=BLUE, alpha=0.7, label="QSP evaluation")
    # Polynomial reconstructed from retracted coefficients
    ax2.plot(x_plot, vals_retracted, color=MAIZE, label="Retracted polynomial")
    ax2.set_xlabel("x")
    ax2.set_ylabel("Value")
    ax2.set_title(f"QSP vs retracted polynomial (degree = {degree})")
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc="best")

    plt.show()


if __name__ == "__main__":
    main()

